/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Icon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  columns?: Array<{
    title?: string
    links?: Array<{
      label?: string
      link?: string
      _key: string
    }>
    _key: string
  }>
  socialLinks?: Array<{
    platform?: string
    link?: string
    _key: string
  }>
  copyright?: string
}

export type Header = {
  _id: string
  _type: 'header'
  _createdAt: string
  _updatedAt: string
  _rev: string
  topBanner?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  navigation?: Array<{
    label?: string
    link?: string
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type GridSection = {
  _type: 'gridSection'
  items?: Array<{
    icon?: Icon
    title?: string
    description?: string
    actions?: Array<{
      label?: string
      link?: string
      variant?: 'primary' | 'secondary'
      _key: string
    }>
    _key: string
  }>
}

export type ContactHeroSection = {
  _type: 'contactHeroSection'
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type FeaturedArticlesSection = {
  _type: 'featuredArticlesSection'
  heading?: string
  articles?: Array<
    {
      _key: string
    } & ArticleReference
  >
}

export type FaqSection = {
  _type: 'faqSection'
  heading?: string
  faqs?: Array<{
    question?: string
    answer?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
          _key: string
        }
    >
    _key: string
  }>
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  text?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageSide?: 'left' | 'right'
}

export type TextSection = {
  _type: 'textSection'
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type HeroSection = {
  _type: 'heroSection'
  heading?: string
  subheading?: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ctaText?: string
  ctaLink?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroSection)
    | ({
        _key: string
      } & TextSection)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & FaqSection)
    | ({
        _key: string
      } & FeaturedArticlesSection)
    | ({
        _key: string
      } & ContactHeroSection)
    | ({
        _key: string
      } & GridSection)
  >
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type ArticleCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articleCategory'
}

export type UserReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'user'
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  headerImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  categories?: Array<
    {
      _key: string
    } & ArticleCategoryReference
  >
  author?: UserReference
  reviewedBy?: UserReference
  relatedProducts?: Array<
    {
      _key: string
    } & ProductReference
  >
  publishedAt?: string
  updatedAt?: string
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
  >
}

export type ArticleCategory = {
  _id: string
  _type: 'articleCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  parent?: ArticleCategoryReference
}

export type User = {
  _id: string
  _type: 'user'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  summary?: string
  designation?: string
  profile?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  biography?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
}

export type CategoryPromotion = {
  _type: 'categoryPromotion'
  active?: boolean
  heading?: string
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  limit?: number
}

export type ProductFeature = {
  _type: 'productFeature'
  key?: string
  value?: string
}

export type BrandReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'brand'
}

export type ProductSpecification = {
  _type: 'productSpecification'
  sku?: string
  brand?: BrandReference
  daysToShip?: number
  lifestage?: string
  primaryFlavor?: string
  weight?: string
  heightIn?: number
  widthIn?: number
}

export type Review = {
  _type: 'review'
  review?: number
  title?: string
  description?: string
  nickname?: string
  email?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  time?: string
}

export type ProductAnswer = {
  _type: 'productAnswer'
  nickname?: string
  answer?: string
  email?: string
  location?: string
  helpful?: number
  notHelpful?: number
}

export type ProductQNA = {
  _type: 'productQNA'
  nickname?: string
  question?: string
  email?: string
  location?: string
  answers?: Array<
    {
      _key: string
    } & ProductAnswer
  >
}

export type ProductVariant = {
  _type: 'productVariant'
  combination?: string
  name?: string
  price?: number
  compareAtPrice?: number
  stock?: number
  sku?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
}

export type ProductOption = {
  _type: 'productOption'
  name?: string
  values?: Array<string>
}

export type Collection = {
  _id: string
  _type: 'collection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
}

export type Brand = {
  _id: string
  _type: 'brand'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  category?: CategoryReference
  subCategory?: CategoryReference
  childCategory?: CategoryReference
  review?: Array<
    {
      _key: string
    } & Review
  >
  productQNA?: Array<
    {
      _key: string
    } & ProductQNA
  >
  price?: number
  compareAtPrice?: number
  stock?: number
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  options?: Array<
    {
      _key: string
    } & ProductOption
  >
  variants?: Array<
    {
      _key: string
    } & ProductVariant
  >
  specifications?: ProductSpecification
  additionalFeatures?: Array<
    {
      _key: string
    } & ProductFeature
  >
  warranty?: string
  directions?: string
  warnings?: string
  ingredients?: string
  guaranteedAnalysis?: string
  moreInformation?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  deliveryMethods?: Array<{
    method?: 'Pickup' | 'SameDay' | 'ShipToMe'
    available?: boolean
    badge?: string
    _key: string
  }>
  repeatDeliveryDiscount?: number
  repeatDeliveryFirstOrderDiscount?: number
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  parent?: CategoryReference
  featuredProducts?: Array<
    {
      _key: string
    } & ProductReference
  >
  trendingProducts?: CategoryPromotion
  bestSellers?: CategoryPromotion
  mostViewed?: CategoryPromotion
  alsoBought?: CategoryPromotion
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Icon
  | Footer
  | Header
  | SanityImageCrop
  | SanityImageHotspot
  | GridSection
  | ContactHeroSection
  | ArticleReference
  | FeaturedArticlesSection
  | FaqSection
  | InfoSection
  | TextSection
  | HeroSection
  | Page
  | Slug
  | ArticleCategoryReference
  | UserReference
  | ProductReference
  | Article
  | ArticleCategory
  | User
  | CategoryPromotion
  | ProductFeature
  | BrandReference
  | ProductSpecification
  | Review
  | ProductAnswer
  | ProductQNA
  | ProductVariant
  | ProductOption
  | Collection
  | Brand
  | CategoryReference
  | Product
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: queries/product.ts
// Variable: productWithVariantValues
// Query: *[_type == 'product']{  name,    price,  "totalCount": count(review.userReviews),  "avgStar": select(    count(review.userReviews) > 0 =>      round(        math::sum(review.userReviews[].review) /        count(review.userReviews),        3      ),    0  ),    "variants": variant[]->{    name,    "key": key.current,    "values": values[]{    price, value    },  },}
export type ProductWithVariantValuesResult = Array<{
  name: string | null
  price: number | null
  totalCount: null
  avgStar: 0
  variants: null
}>

// Source: queries/product.ts
// Variable: productVariantData
// Query: *[_type == 'product']{  name,    price,  "totalCount": count(review.userReviews),  "avgStar": select(    count(review.userReviews) > 0 =>      round(        math::sum(review.userReviews[].review) /        count(review.userReviews),        3      ),    0  ),    "variants": variant[]->{    name,    "key": key.current,    values  },}
export type ProductVariantDataResult = Array<{
  name: string | null
  price: number | null
  totalCount: null
  avgStar: 0
  variants: null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'product\']{\n  name,\n    price,\n  "totalCount": count(review.userReviews),\n  "avgStar": select(\n    count(review.userReviews) > 0 =>\n      round(\n        math::sum(review.userReviews[].review) /\n        count(review.userReviews),\n        3\n      ),\n    0\n  ),\n    "variants": variant[]->{\n    name,\n    "key": key.current,\n    "values": values[]{\n    price, value\n    },\n  },\n}': ProductWithVariantValuesResult
    '*[_type == \'product\']{\n  name,\n    price,\n  "totalCount": count(review.userReviews),\n  "avgStar": select(\n    count(review.userReviews) > 0 =>\n      round(\n        math::sum(review.userReviews[].review) /\n        count(review.userReviews),\n        3\n      ),\n    0\n  ),\n    "variants": variant[]->{\n    name,\n    "key": key.current,\n    values\n  },\n}': ProductVariantDataResult
  }
}
