/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductQNA = {
  _type: 'productQNA'
  nickname?: string
  question?: string
  email?: string
  location?: string
  answers?: Array<{
    nickname?: string
    answer?: string
    email?: string
    location?: string
    helpful?: number
    notHelpful?: number
    _key: string
  }>
}

export type Variant = {
  _type: 'variant'
  name?: string
  key?: string
  values?: Array<{
    price?: number
    value?: string
    _key: string
  }>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type Collection = {
  _id: string
  _type: 'collection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type BrandReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'brand'
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  category?: CategoryReference
  subCategory?: CategoryReference
  childCategory?: CategoryReference
  review?: Array<{
    review?: number
    title?: string
    description?: string
    images?: Array<{
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
      _key: string
    }>
    time?: string
    userDetails?: string
    _key: string
  }>
  productQNA?: Array<
    {
      _key: string
    } & ProductQNA
  >
  stock?: number
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  price?: number
  variant?: Array<
    {
      _key: string
    } & Variant
  >
  specifications?: {
    sku?: string
    brand?: BrandReference
    daysToShip?: number
  }
  additionalFeatures?: Array<{
    key?: string
    value?: string
    _key: string
  }>
  warranty?: string
  directions?: string
  warnings?: string
  ingredients?: string
  guaranteedAnalysis?: string
  moreInformation?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Brand = {
  _id: string
  _type: 'brand'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  parent?: CategoryReference
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ProductQNA
  | Variant
  | SanityImageAssetReference
  | ProductReference
  | Collection
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | CategoryReference
  | BrandReference
  | Product
  | Brand
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: queries/product.ts
// Variable: productWithVariantValues
// Query: *[_type == 'product']{  name,    price,  "totalCount": count(review.userReviews),  "avgStar": select(    count(review.userReviews) > 0 =>      round(        math::sum(review.userReviews[].review) /        count(review.userReviews),        3      ),    0  ),    "variants": variant[]->{    name,    "key": key.current,    "values": values[]{    price, value    },  },}
export type ProductWithVariantValuesResult = Array<{
  name: string | null
  price: number | null
  totalCount: null
  avgStar: 0
  variants: Array<null> | null
}>

// Source: queries/product.ts
// Variable: productVariantData
// Query: *[_type == 'product']{  name,    price,  "totalCount": count(review.userReviews),  "avgStar": select(    count(review.userReviews) > 0 =>      round(        math::sum(review.userReviews[].review) /        count(review.userReviews),        3      ),    0  ),    "variants": variant[]->{    name,    "key": key.current,    values  },}
export type ProductVariantDataResult = Array<{
  name: string | null
  price: number | null
  totalCount: null
  avgStar: 0
  variants: Array<null> | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'product\']{\n  name,\n    price,\n  "totalCount": count(review.userReviews),\n  "avgStar": select(\n    count(review.userReviews) > 0 =>\n      round(\n        math::sum(review.userReviews[].review) /\n        count(review.userReviews),\n        3\n      ),\n    0\n  ),\n    "variants": variant[]->{\n    name,\n    "key": key.current,\n    "values": values[]{\n    price, value\n    },\n  },\n}': ProductWithVariantValuesResult
    '*[_type == \'product\']{\n  name,\n    price,\n  "totalCount": count(review.userReviews),\n  "avgStar": select(\n    count(review.userReviews) > 0 =>\n      round(\n        math::sum(review.userReviews[].review) /\n        count(review.userReviews),\n        3\n      ),\n    0\n  ),\n    "variants": variant[]->{\n    name,\n    "key": key.current,\n    values\n  },\n}': ProductVariantDataResult
  }
}
