/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Icon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Membership = {
  _id: string
  _type: 'membership'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  price?: number
  benefits?: Array<{
    title?: string
    detail?: string
    icon?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _key: string
  }>
  ctaText?: string
  badgeColor?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type Store = {
  _id: string
  _type: 'store'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  address?: string
  phone?: string
  location?: Geopoint
  hours?: Array<{
    day?: string
    time?: string
    _key: string
  }>
  servicesAvailable?: Array<
    {
      _key: string
    } & ServiceReference
  >
  isPharmacy?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  shortDescription?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  benefits?: Array<string>
  serviceUrl?: string
}

export type Promotion = {
  _id: string
  _type: 'promotion'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  text?: string
  link?: string
  type?: 'announcement' | 'hero' | 'ribbon'
  backgroundColor?: Color
  isActive?: boolean
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  canonicalUrl?: string
  noIndex?: boolean
  structuredData?: string
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items?: Array<{
    label?: string
    link?: string
    children?: Array<{
      label?: string
      link?: string
      _key: string
    }>
    featured?: {
      title?: string
      image?: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      link?: string
    }
    _type: 'navItem'
    _key: string
  }>
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  columns?: Array<{
    title?: string
    links?: Array<{
      label?: string
      link?: string
      _key: string
    }>
    _key: string
  }>
  socialLinks?: Array<{
    platform?: string
    link?: string
    _key: string
  }>
  copyright?: string
}

export type Header = {
  _id: string
  _type: 'header'
  _createdAt: string
  _updatedAt: string
  _rev: string
  topBanner?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  navigation?: Array<{
    label?: string
    link?: string
    _key: string
  }>
}

export type ServiceGridSection = {
  _type: 'serviceGridSection'
  heading?: string
  services?: Array<
    {
      _key: string
    } & ServiceReference
  >
}

export type MembershipReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'membership'
}

export type MembershipSection = {
  _type: 'membershipSection'
  heading?: string
  subheading?: string
  tiers?: Array<
    {
      _key: string
    } & MembershipReference
  >
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type ProductListSection = {
  _type: 'productListSection'
  heading?: string
  category?: CategoryReference
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  limit?: number
}

export type EspotSection = {
  _type: 'espotSection'
  name?: string
  html?: string
  previewUrl?: string
}

export type GridSection = {
  _type: 'gridSection'
  items?: Array<{
    icon?: Icon
    title?: string
    description?: string
    actions?: Array<{
      label?: string
      link?: string
      variant?: 'primary' | 'secondary'
      _key: string
    }>
    _key: string
  }>
}

export type ContactHeroSection = {
  _type: 'contactHeroSection'
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type FeaturedArticlesSection = {
  _type: 'featuredArticlesSection'
  heading?: string
  articles?: Array<
    {
      _key: string
    } & ArticleReference
  >
}

export type FaqSection = {
  _type: 'faqSection'
  heading?: string
  faqs?: Array<{
    question?: string
    answer?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
          _key: string
        }
    >
    _key: string
  }>
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  text?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageSide?: 'left' | 'right'
}

export type TextSection = {
  _type: 'textSection'
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type HeroSection = {
  _type: 'heroSection'
  heading?: string
  subheading?: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ctaText?: string
  ctaLink?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  seo?: Seo
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroSection)
    | ({
        _key: string
      } & TextSection)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & FaqSection)
    | ({
        _key: string
      } & FeaturedArticlesSection)
    | ({
        _key: string
      } & ContactHeroSection)
    | ({
        _key: string
      } & GridSection)
    | ({
        _key: string
      } & EspotSection)
    | ({
        _key: string
      } & ProductListSection)
    | ({
        _key: string
      } & MembershipSection)
    | ({
        _key: string
      } & ServiceGridSection)
  >
}

export type ArticleCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articleCategory'
}

export type UserReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'user'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  headerImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  categories?: Array<
    {
      _key: string
    } & ArticleCategoryReference
  >
  author?: UserReference
  reviewedBy?: UserReference
  relatedProducts?: Array<
    {
      _key: string
    } & ProductReference
  >
  publishedAt?: string
  updatedAt?: string
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
  >
}

export type ArticleCategory = {
  _id: string
  _type: 'articleCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  parent?: ArticleCategoryReference
}

export type BreedReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'breed'
}

export type PetProfile = {
  _id: string
  _type: 'petProfile'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  petType?: string
  breed?: BreedReference
  birthday?: string
  weight?: number
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  healthIssues?: Array<string>
}

export type Breed = {
  _id: string
  _type: 'breed'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  petType?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type PetProfileReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'petProfile'
}

export type User = {
  _id: string
  _type: 'user'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  summary?: string
  designation?: string
  profile?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  biography?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  pets?: Array<
    {
      _key: string
    } & PetProfileReference
  >
}

export type ProductBadge = {
  _id: string
  _type: 'productBadge'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  color?: Color
}

export type CategoryPromotion = {
  _type: 'categoryPromotion'
  active?: boolean
  heading?: string
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  limit?: number
}

export type ProductFeature = {
  _type: 'productFeature'
  key?: string
  value?: string
}

export type BrandReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'brand'
}

export type ProductSpecification = {
  _type: 'productSpecification'
  sku?: string
  brand?: BrandReference
  daysToShip?: number
  lifestage?: string
  primaryFlavor?: string
}

export type Review = {
  _id: string
  _type: 'review'
  _createdAt: string
  _updatedAt: string
  _rev: string
  product?: ProductReference
  rating?: 1 | 2 | 3 | 4 | 5
  title?: string
  description?: string
  nickname?: string
  email?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  time?: string
}

export type ProductAnswer = {
  _type: 'productAnswer'
  nickname?: string
  answer?: string
  email?: string
  location?: string
  helpful?: number
  notHelpful?: number
}

export type ProductQNA = {
  _id: string
  _type: 'productQNA'
  _createdAt: string
  _updatedAt: string
  _rev: string
  product?: ProductReference
  nickname?: string
  question?: string
  answers?: Array<
    {
      _key: string
    } & ProductAnswer
  >
}

export type ProductVariant = {
  _type: 'productVariant'
  combination?: string
  name?: string
  price?: number
  compareAtPrice?: number
  stock?: number
  sku?: string
  barcode?: string
  weight?: string
  heightIn?: number
  widthIn?: number
  depthIn?: number
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
}

export type ProductOption = {
  _type: 'productOption'
  name?: string
  values?: Array<string>
}

export type Collection = {
  _id: string
  _type: 'collection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
}

export type ProductBadgeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productBadge'
}

export type ReviewReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'review'
}

export type ProductQNAReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'productQNA'
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  category?: CategoryReference
  subCategory?: CategoryReference
  childCategory?: CategoryReference
  petType?: string
  lifeStage?: 'junior' | 'adult' | 'senior' | 'all'
  healthConsiderations?: Array<string>
  badges?: Array<
    {
      _key: string
    } & ProductBadgeReference
  >
  review?: Array<
    {
      _key: string
    } & ReviewReference
  >
  productQNA?: Array<
    {
      _key: string
    } & ProductQNAReference
  >
  price?: number
  discountPercentage?: number
  rating?: number
  stock?: number
  brand?: BrandReference
  sku?: string
  barcode?: string
  availabilityStatus?: 'in-stock' | 'out-of-stock' | 'backorder' | 'preorder'
  returnPolicy?: string
  shippingInformation?: string
  minimumOrderQuantity?: number
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  options?: Array<
    {
      _key: string
    } & ProductOption
  >
  variants?: Array<
    {
      _key: string
    } & ProductVariant
  >
  specifications?: ProductSpecification
  additionalFeatures?: Array<
    {
      _key: string
    } & ProductFeature
  >
  requiresPrescription?: boolean
  dosageForm?: 'tablet' | 'chewable' | 'topical' | 'injectable' | 'oral-suspension'
  warranty?: string
  directions?: string
  warnings?: string
  ingredients?: string
  guaranteedAnalysis?: string
  moreInformation?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  deliveryMethods?: Array<{
    method?: 'Pickup' | 'SameDay' | 'ShipToMe'
    available?: boolean
    badge?: string
    _key: string
  }>
  repeatDeliveryDiscount?: number
  repeatDeliveryFirstOrderDiscount?: number
  seo?: Seo
  relatedArticles?: Array<
    {
      _key: string
    } & ArticleReference
  >
}

export type Brand = {
  _id: string
  _type: 'brand'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bannerImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  petTypes?: Array<string>
  description?: string
  seo?: Seo
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  petType?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  parent?: CategoryReference
  seo?: Seo
  featuredProducts?: Array<
    {
      _key: string
    } & ProductReference
  >
  trendingProducts?: CategoryPromotion
  bestSellers?: CategoryPromotion
  mostViewed?: CategoryPromotion
  alsoBought?: CategoryPromotion
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Icon
  | Membership
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ServiceReference
  | Store
  | Geopoint
  | Service
  | Promotion
  | Color
  | Seo
  | Navigation
  | Footer
  | Header
  | ServiceGridSection
  | MembershipReference
  | MembershipSection
  | CategoryReference
  | ProductReference
  | ProductListSection
  | EspotSection
  | GridSection
  | ContactHeroSection
  | ArticleReference
  | FeaturedArticlesSection
  | FaqSection
  | InfoSection
  | TextSection
  | HeroSection
  | Page
  | ArticleCategoryReference
  | UserReference
  | Article
  | ArticleCategory
  | BreedReference
  | PetProfile
  | Breed
  | PetProfileReference
  | User
  | ProductBadge
  | CategoryPromotion
  | ProductFeature
  | BrandReference
  | ProductSpecification
  | Review
  | ProductAnswer
  | ProductQNA
  | ProductVariant
  | ProductOption
  | Collection
  | ProductBadgeReference
  | ReviewReference
  | ProductQNAReference
  | Product
  | Brand
  | Category
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: queries/product.ts
// Variable: productWithVariantValues
// Query: *[_type == 'product']{  name,    price,  "totalCount": count(review.userReviews),  "avgStar": select(    count(review.userReviews) > 0 =>      round(        math::sum(review.userReviews[].review) /        count(review.userReviews),        3      ),    0  ),    "variants": variant[]->{    name,    "key": key.current,    "values": values[]{    price, value    },  },}
export type ProductWithVariantValuesResult = Array<{
  name: string | null
  price: number | null
  totalCount: null
  avgStar: 0
  variants: null
}>

// Source: queries/product.ts
// Variable: productVariantData
// Query: *[_type == 'product']{  name,    price,  "totalCount": count(review.userReviews),  "avgStar": select(    count(review.userReviews) > 0 =>      round(        math::sum(review.userReviews[].review) /        count(review.userReviews),        3      ),    0  ),    "variants": variant[]->{    name,    "key": key.current,    values  },}
export type ProductVariantDataResult = Array<{
  name: string | null
  price: number | null
  totalCount: null
  avgStar: 0
  variants: null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'product\']{\n  name,\n    price,\n  "totalCount": count(review.userReviews),\n  "avgStar": select(\n    count(review.userReviews) > 0 =>\n      round(\n        math::sum(review.userReviews[].review) /\n        count(review.userReviews),\n        3\n      ),\n    0\n  ),\n    "variants": variant[]->{\n    name,\n    "key": key.current,\n    "values": values[]{\n    price, value\n    },\n  },\n}': ProductWithVariantValuesResult
    '*[_type == \'product\']{\n  name,\n    price,\n  "totalCount": count(review.userReviews),\n  "avgStar": select(\n    count(review.userReviews) > 0 =>\n      round(\n        math::sum(review.userReviews[].review) /\n        count(review.userReviews),\n        3\n      ),\n    0\n  ),\n    "variants": variant[]->{\n    name,\n    "key": key.current,\n    values\n  },\n}': ProductVariantDataResult
  }
}
